### ISSUE TITLE
esp82xx compatibility?

### ISSUE THREAD

**Issue by rradar** [risinek/esp32-wifi-penetration-tool#18]
I think I checked all the documentation and information and didn't found a esp8266 (or esp8285) mentioned everywhere.

Is it possible (in theory) or are their unsolvable issues hardware or software wise to make this working on a esp82xx?

**Comment by risinek** [comment]
Hi, this project is purely for ESP32 chip. It uses different SDK and API and it is not possible to simply migrate it to ESP8266 platform.

But depending on what your are interested, there are some projects, that implements deauth attacks and some limited packet capture on ESP8266.
Check Spacehuhns projects - https://github.com/SpacehuhnTech/esp8266_deauther
And https://github.com/spacehuhn/PacketMonitor
And there are more.

But ESP8266 has firmware limitations in receive buffer, that allows only 128kb (if i remember it right) of packet to be captured, which is usually not enough for WPA handshakes.
