### ISSUE TITLE
Will it work on ESP32S

### ISSUE THREAD

**Issue by zach67385** [risinek/esp32-wifi-penetration-tool#21]
here is a link to https://www.ebay.co.uk/itm/193648698675
is there support for this/will it work on it.

**Comment by risinek** [comment]
Well it should work, but I haven't tried that, so I can't confirm. [Based on Wiki](https://en.wikipedia.org/wiki/ESP32), it's a name of the kit by Ai-Thinker, that actually uses base ESP32. In that case, it should work just fine.
