### ISSUE TITLE
Flashing via Arduino and Hardware doubt

### ISSUE THREAD

**Issue by morpheuslord** [risinek/esp32-wifi-penetration-tool#23]
hello,
I am new to programming firmware to esp32 and can you tell the libraries and components we need to flash this and 
will this work without the battery and only on a micro-USB connection like a pocket hacking machine.
there are 3 bin files and i have no idea which i need to flash and in which format please help
thank you @risinek @dkbarrett

**Comment by risinek** [comment]
> can you tell the libraries and components we need to flash this

without any modifications from your side, you should ESP-IDF. You can learn more from official documentation https://docs.espressif.com/projects/esp-idf/en/latest/esp32/get-started/index.html

> will this work without the battery and only on a micro-USB connection

yes, assuming that it provides enough power - at least 100mA, but I guess you want to connect it to laptop or directly to a power supply, so then you are fine in most cases.

> there are 3 bin files and i have no idea which i need to flash and in which format please help
 
you need all 3 binaries, but it's all described in [README](https://github.com/risinek/esp32-wifi-penetration-tool#flash)
