### ISSUE TITLE
I tried it with another ESP network, unfortunately it never works

### ISSUE THREAD

**Issue by olebohmbach** [risinek/esp32-wifi-penetration-tool#34]
I tried it with another ESP network, unfortunately it never works
![image](https://user-images.githubusercontent.com/77053238/185742508-b5f6b608-cf93-4b8f-a25a-524b811fc595.png)

**Comment by olebohmbach** [comment]
??

**Comment by risinek** [comment]
I cant help you without any info about the target network.
