### ISSUE TITLE
The firmware is not compiled

### ISSUE THREAD

**Issue by m1khailbr** [risinek/esp32-wifi-penetration-tool#49]
I did everything according to the instructions. The compilation process fails (see photo). What did I do wrong? [photo and log](https://drive.google.com/drive/folders/1K3XXXnmEEUo3D9GqhTRb06BSOgd3NLbZ?usp=sharingl)

**Comment by risinek** [comment]
Sorry, I don't have a capacity to provide a guidance how to build and flash on Windows platform. The compilation error is about MQTT component that is not even part of this project. Are you able to compile some example project provided in ESP-IDF distribution using your current toolchain? Are you able to build this project from master branch without any changes?  
🇺🇦 ✌️
