### ISSUE TITLE
 How does it work?      "Add connectivity by Bluetooth. Add ability to reset via Bluetooth"

### ISSUE THREAD

**Issue by lab37** [risinek/esp32-wifi-penetration-tool#50]
"Add connectivity by Bluetooth. Add ability to reset via Bluetooth"
How can  i  use  the  bluetooth  to  reset  the   esp32?  thanks

**Comment by risinek** [comment]
This project does not support Bluetooth. For general ESP32 support you have to contact Espressif on their forum or read ESP32 documentation first.
