### ISSUE TITLE
i get error while the code is uploading 

### ISSUE THREAD

**Issue by azhar25785** [risinek/esp32-wifi-penetration-tool#64]
even though when i upload the code to my esp32 from arduino ide it works. the upload finishes but i don't see managmentAP ssid in wifi networks available here is the error in the brackets 
(Uploading stub...
Running stub...
Stub running...
Changing baud rate to 115200
Changed.
Unable to perform XMC flash chip startup sequence (Cannot configure port, something went wrong. Original message: PermissionError(13, 'A device attached to the system is not functioning.', None, 31)).
FLASH_CRYPT_CNT 0
ABS_DONE_0 False
Compressed 24016 bytes to 14877...
Compressed 3072 bytes to 103...
Compressed 723248 bytes to 447613...

 is stub and send flash finish)

**Comment by risinek** [comment]
I don't understand the issue. You said that uploading the code using Arduino IDE works, but the title and error says that there was an error while uploading/flashing the code onto the ESP32. If you have problem with flashing the code, it's not related to this project and you should ask on ESP32 forum for help.

**Comment by azhar25785** [comment]
Thanks.... issue resolved my data cable was faulty i think
