### ISSUE TITLE
192.168.4.1 not working on NodeMCU 32S

### ISSUE THREAD

**Issue by AyoubCoding21** [risinek/esp32-wifi-penetration-tool#65]
When I did ur project everything was good, I flashed everything into the NodeMCU 32S, And when I try to access 192.
168.4.1, The browser keeps on loading. I used ESP-IDF
![screen](https://github.com/risinek/esp32-wifi-penetration-tool/assets/120122307/6e692397-bf02-425c-b3b7-690ca8bd69b7)

**Comment by risinek** [comment]
silly question but are you connected to the Management AP right?

**Comment by risinek** [comment]
What was the problem?

**Comment by AyoubCoding21** [comment]
I did not connect to ManagmentAP my bad cos i did not have the usb dongle on my pc
