### ISSUE TITLE
Issues with booting

### ISSUE THREAD

**Issue by Jan64X** [risinek/esp32-wifi-penetration-tool#70]
I'm not 100% sure what esp32 board I have but when I flash it and boot it, it outputs this in PuTTY
<img width="845" alt="screenshot" src="https://github.com/risinek/esp32-wifi-penetration-tool/assets/57019006/a00b3db7-19a0-4c30-9ed4-d0fa1458686a">
Could somebody help please? I need this for a school project...

**Comment by risinek** [comment]
Are you sure you have the ESP IDF setup correctly? The error log shows the path to start with "/home/risinek/esp/..." but I doubt you have same account name as I have. Are you able to build and flash some of the example projects in ESP-IDF?

**Comment by Jan64X** [comment]
Well I used the example binaries in releases and used the windows official flash tool. How should I build and flash the projects? EDIT: I'm also using Windows

**Comment by Jan64X** [comment]
I flashed it again using the binaries in the build/ folder and the Flash download tool, but it still gives me the error in the pic.

**Comment by Jan64X** [comment]
Ok, I'll try reinstalling ESP-IDF, I'll get back to you

**Comment by risinek** [comment]
After a brief googling, it seems like you have unsupported ESP32 chip? Can you figure out what exactly it is? Manufacturer and model name?

**Comment by Jan64X** [comment]
Well, I didn't buy an ESP32 direcly. I bought this thing called fiberpunk for my 3D printer and because I didn't need it anymore I looked it up and on their github page it says that its based on ESP32. Heres the repo: https://github.com/fiberpunk1/Beam-ESP32 . Looks to be ESP32 based but not an actual module: 
![image](https://github.com/risinek/esp32-wifi-penetration-tool/assets/57019006/e2054b3b-2935-4280-b629-6517a3db986b)

**Comment by risinek** [comment]
does it even have wifi module? Anyway this is not a problem of this project, but rather of the compatibility of your chip with ESP-IDF. If you are not able to flash example projects from ESP-IDF, I can't help. Ask on Espressif forums to get help with setting this up.
